### ISSUE TITLE
Storage Scanner not showing items if there are more than 127 pieces of them in the containers

### ISSUE THREAD

**Issue by Precatou** [McJtyMods/RFToolsStorage#4] opened 2020-01-21 16:30 UTC
I have a problem with the Storage Scanner. I'm using it to scan minecolonies warehouse which has close to 20 racks containing random items. I noticed that the scanner displays most of the items just fine, but not those which I have more than 127 pieces. It can be anything. Like oak planks, torches, it doesn't matter. Upto 127 is shown alright, but if I add one more to any of the scanned inventories then the icon turns blank and the amount number disappears until I reach 257 which is shown as 1. So, there's 4 full stacks plus 1 in the inventories. Then I can see the number increase to 127 until sixth full stack is reached. Then the item and the amount number becomes blank until I reach 8 full stacks plus 1. It's a bit weird, but that's how it appears to work.

I can't see any related errors in the log files. The attached picture is from the scanner. Observe the area marked with red color. Those are the blank items.

rftoolsstorage-1.14-0.0.7-alpha.jar
![scanner](https://user-images.githubusercontent.com/44037882/72821569-58fe6d80-3c79-11ea-8825-f46e86caa6b0.PNG)

**Comment by McJty** [comment] 2020-01-21 17:22
This is most likely an issue with the warehouse because with normal chests/inventories the storage scanner is perfectly capable of showing more than 127 items. I do that all the time in my own lets plays

**Comment by Precatou** [comment] 2020-01-21 21:11
I removed all mods except for the following. I create a new world. Placed a Storage Scanner, a Coal power generator and a chest to the ground. Then I started loading oak planks into the chest. As soon as two full stacks were placed in the oak planks item in the Scanner turned into a blank item and the amount number disappeared. It worked exactly how I explained earlier.

mcjtylib-1.14-3.5.17-alpha
rftoolsbase-1.14-0.0.12-alpha
rftoolsbuilder-1.14-1.2.12-alpha
rftoolspower-1.14-1.2.12-alpha
rftoolsstorage-1.14-0.0.7-alpha
rftoolsutility-1.14-1.2.14-alpha

**Comment by Precatou** [comment] 2020-02-02 12:53
I did some more testing. I installed the rftools version which works on MC1.12.2 and it worked flawlessly. I compared the experiences I had with that with the rftools version mentioned above on MC1.14.4 and noticed that on top of the problems listed above the storage scanner appears to have some issues with the GUI as well.

For example when I grab the scan range slider and move it around the range value nor the slider itself doesn't update real time. They do update when I release the slider, not while I drag it which means I cannot see which range value I have chosen until I let go of the slider. Same problem with the slider controlling the list of items when there are more than a screenful of them.

The power indicator does not update real time either. The same indicator in Coal Power Generator works fine.

I'm quite puzzled if I'm the only one having this issue.

**Comment by McJty** [comment] 2020-02-02 13:18
I will try again if I can reproduce this

**Comment by Precatou** [comment] 2020-02-07 15:30
Is it fair to assume you weren't able to reproduce the issue?

**Comment by McJty** [comment] 2020-02-07 15:38
Ah well I couldn't reproduce it in my 1.15 port but I forgot to test the 1.14 version. I'll try to remember this time :-)

**Comment by McJty** [comment] 2020-02-08 05:14
I could reproduce it now. Seems to be broken on 1.14. As I'm busy moving everything to 1.15 right now I'm not sure if I'm going to fix it now since it works fine on 1.15. I'll think about it

**Comment by Precatou** [comment] 2020-02-08 12:22
Thanks for replicating the problem. I was about to start testing different Java versions, but apparently that's not necessary anymore.

The mod is used in Valhelsia modpack and it would be great for managing the minecolonies storage house. Anyway, I would appreciate the fix, but of course it'll be entirely up to you to decide what to do with it.

**Comment by McJty** [comment] 2020-02-23 06:01
Will be fixed next release (today)

**Closed as completed by McJty** 2020-02-23 06:01 UTC

**Comment by KajesLorian** [comment] 2020-09-11 22:01
ETA on next release? We are still on version rftoolsstorage-1.14-0.0.7-alpha and the problem persists.

**Comment by McJty** [comment] 2020-09-12 02:50
I no longer work on 1.14.4. This is fixed in 1.15.2 and later
