### ISSUE TITLE
Modular Storage Initial TPS Lag from Server and MAJOR FPS Drop

### ISSUE THREAD

**Issue by desagas** [McJtyMods/RFToolsStorage#43] opened 2021-03-02 21:34 UTC
Playing ATM6 1.5.3b, rftoolsstorage-1.16-2.0.10, and rftoolsbase-1.16-2.0.10; when FIRST opening a MS, tier 4 module inside, when communicating between server and client, there is about a5 to 10 second delay for full modules, and about a 5 second delay for partially full modules, and at a minimum, around a 2 to 3 second delay for the MS to update the contents of the module. This is not only taking time, but it is causing a drop in TPS, so much so, that recommended chunk view distance is halved, at min.

Further, regarding FPS, when lookin inside a MS, with tier 4 module, and all the other tiers as well, my FPS drops from 82 average, to around 8 average, and, the overlay display is duplicated ... below is a video of what happens (I had already opened the MS, so this video only shows the major FPS drop).

https://youtu.be/5po6Ld7uogQ

**Comment by McJty** [comment] 2021-03-03 06:17
I will investigate

**Comment by McJty** [comment] 2021-03-05 04:55
BTW, if you have the double tooltip then that means you're not using latest version

**Comment by McJty** [comment] 2021-03-05 05:29
I cannot reproduce this locally. Question: is the modular storage that you're looking at one that is updated often? i.e. new items getting inserted or removed?

**Comment by desagas** [comment] 2021-03-05 17:31
I will check for additional updates ... I am assuming you mean updates that come after the before mentioned version where this is happening? I will update to the latest version on both client and server, and I will get back to you.

As for the modular storage, I have four of them. I have accessed them a couple of different ways, which I forgot to mention:
1. Via refined storage external storage ... significantly drops server tps, while still playable on low server render, local client render makes no difference. This method, when turning on my RS system, takes about 2 seconds to be able to access the Modular Storage Units.
2. Via hand access: I only access them once in a while. As I mentioned above, if I have accessed them recently, there is not a delay, but FPS massively drops, which hopefully your update fixes. As for the delay mentioned, this is only when trying to open them after a while of not opening them.
 --> I do have a massive filter in both as well. But, I tried adding and removing it, and no difference was made, so I did not mention it.

Either way, ill get back to you after a bit more playing around, in the next couple of days.

**Comment by desagas** [comment] 2021-03-05 17:42
Update ... FPS is still massively dropping on .11 of your mod ..., duplicate display is gone, nice!

As for Delay, here is a video, in the latest versions, still on forge 1.16.5.36.0.43: https://youtu.be/9C883Mp59JE

And, OS, I am on a Server to Client bridged connection, with only Minecraft running through the network, at 100MB/S, so, I am sure it is not connection related ...

Also, interesting note: TOP allows me to see its contents INSTANTLY, when hovering.

**Comment by Seceroth** [comment] 2021-03-18 11:05
Also having this issue.
I can add that the storage scanner is able to access the modular storage blocks instantly without lag on server or client, but I can't use it with anything that reads/interacts with inventories because it does not expose the inventories itself to Integrated Dynamics for example. Also accessing the Modular storages with ID is causing massive lag, like it's constantly syncing the entire inventory every couple of ticks.
Playing Enigmatica 6, version 0.4.3.

**Comment by McJty** [comment] 2021-03-18 12:16
Do you also have this issue if you only connect the storage scanner to vanilla chests and/or rftools storages? I suspect it must be some kind of mod interaction with one of the mods you're using.

As to not being able to use it on anything that interacts with inventories that's normal. The storage scanner can only work with inventories directly

**Comment by Seceroth** [comment] 2021-03-18 12:59
Not sure I understand the question here, sorry. The Scanner is not causing any issues for me, just the Modular Storage blocks once a storage module has been inserted. Opening the Modular storage block that has a 500 item Storage module will cause about 10 seconds of both client fps lag and server lag, even when closing the interface. Both with an ID Item interface and without one attached. Whether a Scanner has this Modular storage block in it's list or not doesn't matter. Once the contents of the Modular Storage block have been synced with the client though, the lag is gone and it can be interacted with normally, though the fps is certainly taking a big hit still while browsing the items.

**Comment by McJty** [comment] 2021-03-18 13:11
Ah ok. Well I haven't been able to reproduce that problem

**Comment by desagas** [comment] 2021-03-18 14:51
I wish I could test this with just RFTools, but, my server PC is dead, and with silicon shortages, it could be months. Ugh.

**Comment by Seceroth** [comment] 2021-03-19 11:30
Apologies if this is not relevant to this issue, but in the same world as where the Modular Storage blocks are lagging, I got a server timeout crash that mentions mcjty in the log when using an ID network attached to them.

https://github.com/CyclopsMC/IntegratedDynamics/issues/1008#issue-834759897

Maybe it's related somehow?

**Comment by jacket430** [comment] 2021-12-01 13:10
I know this is an old issue so I apologize if this isn't the right place, but I am using the modular storage in All The Mods 6 (1.8.10) just like the original poster and I have severe fps drop as well. Game goes down to single digits. I'm not sure if it's a problem with the pack, but it's gotta be with _something_ in the pack. Kinda hard to pinpoint when there are so many mods.

**Comment by McJty** [comment] 2021-12-01 13:38
@jacket430 what version?

**Comment by jacket430** [comment] 2021-12-02 05:08
It looks like the version included with the latest version of All The Mods 6 is rftools storage version 2.0.13, base version 2.0.11, McJtyLib 5.0.23.

**Comment by McJty** [comment] 2021-12-02 05:46
It's possible that the latest versions of my mods fixes (or at least improves) this problem

**Comment by McJty** [comment] 2022-01-08 09:30
I think I might have finally fixed this. Next version should get performance back

**Closed as completed by McJty** 2022-01-08 09:30 UTC
