### ISSUE TITLE
Storage Scanner GUI crash 

### ISSUE THREAD

**Issue by Halfdeaf** [McJtyMods/RFToolsStorage#2] opened 2019-12-04 23:48 UTC
I got this crash today while testing the storage scanner in Enigmatica 4. I was setting it up to scan a bank of storage drawers. I'm not sure but I think it triggered when I moved the mouse off-screen and activated a window of the screen (outside Minecraft)

[crash-2019-12-04_23.32.12-client.txt](https://github.com/McJtyMods/RFToolsStorage/files/3924427/crash-2019-12-04_23.32.12-client.txt)

Also, the scanner is not reading Storage Drawers correctly, not sure if it's even supposed to work at this point, let me know if you want me to make a separate issue for that

**Comment by Halfdeaf** [comment] 2019-12-05 01:34
I did some more testing and it definitely has to do with minimizing Minecraft. Tested on Storage Scanner, Modular Storage, Dimensional Cell and Dialing Device. So it's not just RFTstorage

**Comment by Yamza** [comment] 2020-02-13 03:13
Seems like this is still an issue in 1.15.2. Player said it was caused by taking a screenshot via print screen. https://hatebin.com/zksawoowqy

**Comment by McJty** [comment] 2020-02-23 06:05
Will be fixed next release

**Closed by McJty** 2020-02-23 06:05 UTC
